# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Noetic Nought
    url: https://punchagan.muse-amuse.in
  - name: Baali सतत
    url: https://baali.muse-amuse.in
  - name: muse-amuse.in home page
    url: https://muse-amuse.in
  - name: Ukulele tutorials
    url: https://ukulele.muse-amuse.in
  - name: KD Home
    url: http://kadambarid.in
  - name: Unframed
    url: https://unframed.in
    maxRedirects: 5

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ause-amuse Status page
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status page for sites hosted on muse-amuse.in server
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
