owner: muse-amuse 
repo: status

sites:
  - name: Noetic Nought
    url: https://punchagan.muse-amuse.in
  - name: Baali सतत
    url: https://baali.muse-amuse.in
  - name: muse-amuse.in home page
    url: https://muse-amuse.in
  - name: TIKS RSVP app
    url: https://rsvp.tiks-ultimate.in/
    maxRedirects: 5
  - name: KD Home
    url: http://kadambarid.in
  - name: Unframed
    url: https://unframed.in
    maxRedirects: 5

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.muse-amuse.in
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: muse-amuse Status page
  introTitle: Status page for sites hosted on muse-amuse.in server
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "4,14,24,34,44,54 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
